// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/summary.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Identifier    string                 `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomUser) Reset() {
	*x = CustomUser{}
	mi := &file_proto_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomUser) ProtoMessage() {}

func (x *CustomUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomUser.ProtoReflect.Descriptor instead.
func (*CustomUser) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{0}
}

func (x *CustomUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomUser) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CustomUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Faculty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Faculty) Reset() {
	*x = Faculty{}
	mi := &file_proto_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Faculty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faculty) ProtoMessage() {}

func (x *Faculty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faculty.ProtoReflect.Descriptor instead.
func (*Faculty) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{1}
}

func (x *Faculty) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Faculty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StudyProgram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Degree        string                 `protobuf:"bytes,3,opt,name=degree,proto3" json:"degree,omitempty"`
	Faculty       *Faculty               `protobuf:"bytes,4,opt,name=faculty,proto3" json:"faculty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyProgram) Reset() {
	*x = StudyProgram{}
	mi := &file_proto_summary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyProgram) ProtoMessage() {}

func (x *StudyProgram) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyProgram.ProtoReflect.Descriptor instead.
func (*StudyProgram) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{2}
}

func (x *StudyProgram) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudyProgram) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudyProgram) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *StudyProgram) GetFaculty() *Faculty {
	if x != nil {
		return x.Faculty
	}
	return nil
}

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nim           string                 `protobuf:"bytes,2,opt,name=nim,proto3" json:"nim,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	StudyProgram  *StudyProgram          `protobuf:"bytes,5,opt,name=study_program,json=studyProgram,proto3" json:"study_program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_proto_summary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{3}
}

func (x *Student) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Student) GetNim() string {
	if x != nil {
		return x.Nim
	}
	return ""
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Student) GetStudyProgram() *StudyProgram {
	if x != nil {
		return x.StudyProgram
	}
	return nil
}

type Lecturer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nip           string                 `protobuf:"bytes,2,opt,name=nip,proto3" json:"nip,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	TotalStudent  int32                  `protobuf:"varint,5,opt,name=total_student,json=totalStudent,proto3" json:"total_student,omitempty"`
	StudyProgram  *StudyProgram          `protobuf:"bytes,6,opt,name=study_program,json=studyProgram,proto3" json:"study_program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lecturer) Reset() {
	*x = Lecturer{}
	mi := &file_proto_summary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lecturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lecturer) ProtoMessage() {}

func (x *Lecturer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lecturer.ProtoReflect.Descriptor instead.
func (*Lecturer) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{4}
}

func (x *Lecturer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lecturer) GetNip() string {
	if x != nil {
		return x.Nip
	}
	return ""
}

func (x *Lecturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lecturer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Lecturer) GetTotalStudent() int32 {
	if x != nil {
		return x.TotalStudent
	}
	return 0
}

func (x *Lecturer) GetStudyProgram() *StudyProgram {
	if x != nil {
		return x.StudyProgram
	}
	return nil
}

type ThesisInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Progress      string                 `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThesisInfo) Reset() {
	*x = ThesisInfo{}
	mi := &file_proto_summary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThesisInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThesisInfo) ProtoMessage() {}

func (x *ThesisInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThesisInfo.ProtoReflect.Descriptor instead.
func (*ThesisInfo) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{5}
}

func (x *ThesisInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ThesisInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ThesisInfo) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

type MessageSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsText          bool                   `protobuf:"varint,2,opt,name=is_text,json=isText,proto3" json:"is_text,omitempty"`
	Text            string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	FileUrl         string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileType        string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Sender          *CustomUser            `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,7,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	Timestamp       string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageSummary) Reset() {
	*x = MessageSummary{}
	mi := &file_proto_summary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSummary) ProtoMessage() {}

func (x *MessageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSummary.ProtoReflect.Descriptor instead.
func (*MessageSummary) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{6}
}

func (x *MessageSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageSummary) GetIsText() bool {
	if x != nil {
		return x.IsText
	}
	return false
}

func (x *MessageSummary) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageSummary) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *MessageSummary) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *MessageSummary) GetSender() *CustomUser {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessageSummary) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *MessageSummary) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TaskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionStatus string                 `protobuf:"bytes,2,opt,name=session_status,json=sessionStatus,proto3" json:"session_status,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Owner         *CustomUser            `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Student       *Student               `protobuf:"bytes,7,opt,name=student,proto3" json:"student,omitempty"`
	Supervisors   []*Lecturer            `protobuf:"bytes,8,rep,name=supervisors,proto3" json:"supervisors,omitempty"`
	ThesisInfo    *ThesisInfo            `protobuf:"bytes,9,opt,name=thesis_info,json=thesisInfo,proto3" json:"thesis_info,omitempty"`
	Messages      []*MessageSummary      `protobuf:"bytes,10,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSummary) Reset() {
	*x = TaskSummary{}
	mi := &file_proto_summary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSummary) ProtoMessage() {}

func (x *TaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSummary.ProtoReflect.Descriptor instead.
func (*TaskSummary) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{7}
}

func (x *TaskSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskSummary) GetSessionStatus() string {
	if x != nil {
		return x.SessionStatus
	}
	return ""
}

func (x *TaskSummary) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TaskSummary) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *TaskSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TaskSummary) GetOwner() *CustomUser {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *TaskSummary) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *TaskSummary) GetSupervisors() []*Lecturer {
	if x != nil {
		return x.Supervisors
	}
	return nil
}

func (x *TaskSummary) GetThesisInfo() *ThesisInfo {
	if x != nil {
		return x.ThesisInfo
	}
	return nil
}

func (x *TaskSummary) GetMessages() []*MessageSummary {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskSummary           `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_proto_summary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{8}
}

func (x *SummaryRequest) GetTask() *TaskSummary {
	if x != nil {
		return x.Task
	}
	return nil
}

type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_proto_summary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_summary_proto_rawDescGZIP(), []int{9}
}

func (x *SummaryResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummaryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_summary_proto protoreflect.FileDescriptor

const file_proto_summary_proto_rawDesc = "" +
	"\n" +
	"\x13proto/summary.proto\x12\asummary\"d\n" +
	"\n" +
	"CustomUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"-\n" +
	"\aFaculty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"v\n" +
	"\fStudyProgram\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06degree\x18\x03 \x01(\tR\x06degree\x12*\n" +
	"\afaculty\x18\x04 \x01(\v2\x10.summary.FacultyR\afaculty\"\x91\x01\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03nim\x18\x02 \x01(\tR\x03nim\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12:\n" +
	"\rstudy_program\x18\x05 \x01(\v2\x15.summary.StudyProgramR\fstudyProgram\"\xb7\x01\n" +
	"\bLecturer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03nip\x18\x02 \x01(\tR\x03nip\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12#\n" +
	"\rtotal_student\x18\x05 \x01(\x05R\ftotalStudent\x12:\n" +
	"\rstudy_program\x18\x06 \x01(\v2\x15.summary.StudyProgramR\fstudyProgram\"`\n" +
	"\n" +
	"ThesisInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\tR\bprogress\"\xfc\x01\n" +
	"\x0eMessageSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ais_text\x18\x02 \x01(\bR\x06isText\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12+\n" +
	"\x06sender\x18\x06 \x01(\v2\x13.summary.CustomUserR\x06sender\x12*\n" +
	"\x11parent_message_id\x18\a \x01(\tR\x0fparentMessageId\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\"\xa3\x03\n" +
	"\vTaskSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0esession_status\x18\x02 \x01(\tR\rsessionStatus\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x04 \x01(\tR\aendedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12)\n" +
	"\x05owner\x18\x06 \x01(\v2\x13.summary.CustomUserR\x05owner\x12*\n" +
	"\astudent\x18\a \x01(\v2\x10.summary.StudentR\astudent\x123\n" +
	"\vsupervisors\x18\b \x03(\v2\x11.summary.LecturerR\vsupervisors\x124\n" +
	"\vthesis_info\x18\t \x01(\v2\x13.summary.ThesisInfoR\n" +
	"thesisInfo\x123\n" +
	"\bmessages\x18\n" +
	" \x03(\v2\x17.summary.MessageSummaryR\bmessages\":\n" +
	"\x0eSummaryRequest\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.summary.TaskSummaryR\x04task\"b\n" +
	"\x0fSummaryResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2V\n" +
	"\x0eSummaryService\x12D\n" +
	"\x0fGenerateSummary\x12\x17.summary.SummaryRequest\x1a\x18.summary.SummaryResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_summary_proto_rawDescOnce sync.Once
	file_proto_summary_proto_rawDescData []byte
)

func file_proto_summary_proto_rawDescGZIP() []byte {
	file_proto_summary_proto_rawDescOnce.Do(func() {
		file_proto_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_summary_proto_rawDesc), len(file_proto_summary_proto_rawDesc)))
	})
	return file_proto_summary_proto_rawDescData
}

var file_proto_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_summary_proto_goTypes = []any{
	(*CustomUser)(nil),      // 0: summary.CustomUser
	(*Faculty)(nil),         // 1: summary.Faculty
	(*StudyProgram)(nil),    // 2: summary.StudyProgram
	(*Student)(nil),         // 3: summary.Student
	(*Lecturer)(nil),        // 4: summary.Lecturer
	(*ThesisInfo)(nil),      // 5: summary.ThesisInfo
	(*MessageSummary)(nil),  // 6: summary.MessageSummary
	(*TaskSummary)(nil),     // 7: summary.TaskSummary
	(*SummaryRequest)(nil),  // 8: summary.SummaryRequest
	(*SummaryResponse)(nil), // 9: summary.SummaryResponse
}
var file_proto_summary_proto_depIdxs = []int32{
	1,  // 0: summary.StudyProgram.faculty:type_name -> summary.Faculty
	2,  // 1: summary.Student.study_program:type_name -> summary.StudyProgram
	2,  // 2: summary.Lecturer.study_program:type_name -> summary.StudyProgram
	0,  // 3: summary.MessageSummary.sender:type_name -> summary.CustomUser
	0,  // 4: summary.TaskSummary.owner:type_name -> summary.CustomUser
	3,  // 5: summary.TaskSummary.student:type_name -> summary.Student
	4,  // 6: summary.TaskSummary.supervisors:type_name -> summary.Lecturer
	5,  // 7: summary.TaskSummary.thesis_info:type_name -> summary.ThesisInfo
	6,  // 8: summary.TaskSummary.messages:type_name -> summary.MessageSummary
	7,  // 9: summary.SummaryRequest.task:type_name -> summary.TaskSummary
	8,  // 10: summary.SummaryService.GenerateSummary:input_type -> summary.SummaryRequest
	9,  // 11: summary.SummaryService.GenerateSummary:output_type -> summary.SummaryResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_summary_proto_init() }
func file_proto_summary_proto_init() {
	if File_proto_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_summary_proto_rawDesc), len(file_proto_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_summary_proto_goTypes,
		DependencyIndexes: file_proto_summary_proto_depIdxs,
		MessageInfos:      file_proto_summary_proto_msgTypes,
	}.Build()
	File_proto_summary_proto = out.File
	file_proto_summary_proto_goTypes = nil
	file_proto_summary_proto_depIdxs = nil
}
